version: '2'

services:
  activemq:
    build: .    
    container_name: amq
    # volumes_from:
      # - data
    ports:
      - "61616:61616"
      - "8161:8161" 
 # data:
    # image: alpine:latest
    # container_name: data
    # volumes:
      # - data:/opt/activemq/conf/
# volumes:
  # data:
